### ISSUE TITLE
Service used in test no longer available

### ISSUE THREAD

**Issue by eloyekunle** [tiaguinho/gosoap#14]
One of the SOAP services currently used in `soap_test.go` https://domains.livedns.co.il/API/DomainsAPI.asmx?WSDL is no longer available.
As a result, the WSDL definitions are not built and the test cases do not pass.

**NOTE**: This is actually different from the reason Travis tests aren't passing as I can see from the Travis logs. I've reproduced Travis' issue locally and still looking into that one. Basically, to reproduce it, you'll run into this one first.

**Comment by hbobenicio** [comment]
Maybe running a custom mock soap server would be better for integration testing, instead of relying on external ones (which could potentially be unavailable anytime).
