### ISSUE TITLE
URL does not work

### ISSUE THREAD

**Issue by miha-** [tiaguinho/gosoap#16]
hi

issue with url. Wsdl is downloaded from url but request is then not send to URL, after doing soap.Call.
I traced with wireshark and nothing is send.

tnx

`func main() {
	soap, err := gosoap.SoapClient("http://172.31.1.52/wsdl/pbx900.wsdl")
	if err != nil {
		fmt.Errorf("error not expected: %s", err)
	}

	soap.URL = "http://172.31.1.52/PBX0/user.soap"
	params := gosoap.Params{
		"user":   "test",
		"appl":   "test",
		"v":      true,
		"v501":   true,
		"v700":   true,
		"v800":   true,
		"vx1000": true,
	}

	err = soap.Call("Initialize", params)

	if err != nil {
		fmt.Errorf("error in soap call: %s", err)
	}

	var r interface{}
	soap.Unmarshal(&r)
	fmt.Println(r)

}
`

**Comment by tiaguinho** [comment]
@miha- can you test the newest version of the package?

**Comment by miha-** [comment]
it is ok with newer version.
