### ISSUE TITLE
It's not working when TargetNamespace is empty

### ISSUE THREAD

**Issue by kientv** [tiaguinho/gosoap#19]
In my case: `Definitions.Types[0].XsdSchema[0].TargetNamespace` is empty

\<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://impl.bulkSms.ws/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://impl.bulkSms.ws/" name="CcApi">
....

**Comment by tiaguinho** [comment]
@kientv this still happens with the newest version of the package?
