### ISSUE TITLE
Custom encoder vs standard library

### ISSUE THREAD

**Issue by nazwa** [tiaguinho/gosoap#23]
Hi @tiaguinho ! 

Great work on the library! Just wanted to ask why did you decide to write a custom encoder as opposed to using the standard to marshal Params (`recursiveEncode`)?

Thanks!

**Comment by tiaguinho** [comment]
@nazwa can you confirm if you can do this in the newest version of the package?

**Comment by nazwa** [comment]
Ahh closing as this it no longer relevant!
