### ISSUE TITLE
Unable to find a  c.Definitions.Services[0].Ports[0].SoapAddresses[0].Location

### ISSUE THREAD

**Issue by vivekkrazybee** [tiaguinho/gosoap#25]
Thanks for this lib. I am getting the following error. Please help me.
Code:
soap, err := gosoap.SoapClient(`https://svn.apache.org/repos/asf/airavata/sandbox/xbaya-web/test/Calculator.wsdl`)
	if err != nil {
		fmt.Println("error not expected: %s", err)
	}
	fmt.Println("response :", soap)
	err = soap.Call("NaradaApiService", gosoap.Params{})
	if err != nil {
		fmt.Errorf("error in soap call: %s", err)
	}
Error :
 goroutine 1 [running]:
github.com/tiaguinho/gosoap.(*Client).Call(0xc4204441c0, 0x6cceca, 0x10, 0xc420468510, 0x0, 0x0)
	/home/vivek/go/src/github.com/tiaguinho/gosoap/soap.go:90 +0x5e6

**Comment by tiaguinho** [comment]
@vivekkrazybee we have changed a lot of the package, can you test and tell me if this still happens with the newest version?
