### ISSUE TITLE
Alter Params to support nested requests

### ISSUE THREAD

**Issue by LegendOfGIT** [tiaguinho/gosoap#3]
In my case, i have to consume a soap webservice with a nested request structure:

`
<request>
  <customer>
    <customerId>123</customerId>
  </customer>
</request>
`

Since Params is from type map[string]string, it is impossible to model this kind of request.
Is there a possibility to change the type of Params to map[string]interface{} ?

**Comment by mamapi** [comment]
I have the same problem

**Comment by Fale** [comment]
This is the same of #7 and is implemented in #8

**Comment by LegendOfGIT** [comment]
Kewl.
I will give it a try in the next few weeks.
I close the issue for now.
In case something's wrong with the implementation, I would open another issue or set up a PR to fix it.

**Comment by LegendOfGIT** [comment]
@Fale
Thanks for your improvement :)
