### ISSUE TITLE
Run example test

### ISSUE THREAD

**Issue by ramolec** [tiaguinho/gosoap#30]
Hi, I'm trying to run the readme sample. I'm having trouble on two lines.

Problem1: multiple-value soap.Call() in single-value contextgo
Line 36
`err = soap.Call("GetIpLocation", params)
	if err != nil {
		log.Fatalf("Call error: %s", err)
	}`

Problem2: soap.Unmarshal undefined (type *gosoap.Client has no field or method Unmarshal)go
Line 41
`soap.Unmarshal(&r)`

Can anybody help me?

**Comment by tbschneider** [comment]
This changes works for me.

Line 36
`res, err := soap.Call("GetIpLocation", params)`

Line 41
`res.Unmarshal(&r)`
