### ISSUE TITLE
Create tag or release

### ISSUE THREAD

**Issue by jaiiali** [tiaguinho/gosoap#33]
create a release or add a tag on the repo for convenience of pinning the version when used as a dependency

**Comment by CampNowhere** [comment]
@tiaguinho Please do this. API compatibility has been broken between your last release and now and this is a serious issue.

**Comment by DanielRuf** [comment]
Bump.

Pleas elet me know if you need additional maintainers.

**Comment by DanielRuf** [comment]
Bump.

Please let me know if you need additional maintainers.

**Comment by tiaguinho** [comment]
Hi @DanielRuf, it will be very nice to have you on board.
Can you please help close some issues before I add you as maintainer?

Thank you.
