### ISSUE TITLE
Create SoapClient with a configured HttpClient

### ISSUE THREAD

**Issue by ashkanF** [tiaguinho/gosoap#38]
Hi,

I'm trying to construct a SoapClient with a configured HttpClient so I can skip certificate verifications. Something like this:

	package mypackage
	
	import (
		"crypto/tls"
		"log"
		"net/http"
	
		soap "github.com/tiaguinho/gosoap"
	)
	
	// NewClient creates a SOAP client.
	func NewClient(wsdlUrl string) (*soap.Client, error) {
		transport := &http.Transport{
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: true,
			},
		}
	
		httpClient := &http.Client{Transport: transport}
	
		client ,err := soap.SoapClient(wsdlUrl) // <-- Fails here
		if err != nil {
			return nil, err
		}
	
		client.HttpClient = httpClient
	
		return client, nil
	}

However, it is not working since it will fail even when it tries to get the `wsdl` data!
I just wonder if there is any workaround for this issue or if I'm doing something wrong?
If not, would be really appreciated if we could have it as an enhancement for this package.

Thanks in advance. :)

**Comment by highercomve** [comment]
I created a PR in order to enable that feature

https://github.com/tiaguinho/gosoap/issues/38

**Comment by xhit** [comment]
> 
> 
> I created a PR in order to enable that feature
> 
> #38

The pull request is #44
