### ISSUE TITLE
doRequest status code handling

### ISSUE THREAD

**Issue by Ekizare** [tiaguinho/gosoap#66]
Hello.

There is no handling for HTTP status code in [doRequest](https://github.com/tiaguinho/gosoap/blob/master/soap.go#L225) method. It can be useful as debug info and for resolving some of the errors. I presume the status code should be logged or even return an error if it is not between 200 and 400. 

So, I can create a pull request if needed.

**Comment by tiaguinho** [comment]
Hi @Ekizare,

Will be very good if you open a PR with this feature.
